include:
  - project: 'cyberfusion/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/python.yml'

stages:
  - test
  - build
  - publish

unit test:
  stage: test
  image: python:3.9
  script:
    - pip install --no-cache-dir -r requirements/test.txt
    - cp $CI_PROJECT_DIR/virtualisation-resource-distributor.sqlite3 /tmp/virtualisation-resource-distributor.sqlite3
    - DATABASE_PATH=/tmp/virtualisation-resource-distributor.sqlite3 pytest -vvv --cov-branch --cov=virtualisation_resource_distributor --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
